### ISSUE TITLE
Exercise 1 Questions

### ISSUE THREAD

**Issue by anoonan** [jswizards/Homework#1]
Hey Ryan,

So I think I have a basic understanding of the XMLHTTPRequest object. What I don't understand is "allows for XHR with reduced boilerplate". I'm a little nervous to google is in case examples come up, do you think it's ok to Google, or have a link to something I can read about it?

**Comment by protocolsix** [comment]
XHR -> **X**ml **H**ttp **R**equest

Boilerplate -> "boilerplate code or boilerplate is the sections of code that have to be included in many places with little or no alteration." (https://en.wikipedia.org/wiki/Boilerplate_code)

Boilerplate is basically stuff you have to do over and over that is always the same and can usually be abstracted away somehow (our goal in this exercise is to build this abstraction).

**Comment by protocolsix** [comment]
I'll start working on a glossary of software vernacular that you should be familiar with.

**Comment by anoonan** [comment]
Well I feel dumb now. Ok I think I got this.

**Comment by protocolsix** [comment]
No it's fine. I totally dropped some DSL (domain-specific language) just assuming you'd know.
