### ISSUE TITLE
Bug Fixes

### ISSUE THREAD

**Issue by anoonan** [jswizards/Homework#2]
Ok so this is kind of for me since I have to get back to real work. The script is obviously is broken. I'm getting the following error: 

```
Mixed Content: The page at 'https://developer.mozilla.org/en-US/docs/AJAX/Getting_Started#Step_1_â_How_to_make_an_HTTP_request' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://api.openweathermap.org/data/2.5/weather?id=5391959'. This request has been blocked; the content must be served over HTTPS.  

```

I still need to do a little more reading/re-reading to completely understand what is going on/what I need to do. 

I also don't think my function is correct. I might be trying to do something too difficult.

**Comment by protocolsix** [comment]
https://github.com/jswizards/Homework/blob/master/exercise_one.js#L5

Try it on a non-https web page. (e.g. http://www.nytimes.com/ )

**Comment by protocolsix** [comment]
Alternatively, try this URL which should work on secure (https) pages:

```
https://api.github.com/repos/jswizards/Homework/contributors
```
